from os import mkdir
from os.path import join as pathjoin, abspath, dirname
from shutil import rmtree, copy as shutilcopy

from re import compile as re_compile

from sys import stderr


class CodeGen:
    def __init__(self, args, ctx):
        self.args = args
        self.out_dir = abspath(args.out_dir)
        self.templates_path = None
        self.ctx = ctx

        self._generated_files = []
        self._key_re = re_compile('@(\S+?)@')

        out_dir_overwrite = args.out_dir_overwrite
        print(
            f"Output dir: {self.out_dir} {'(not overwritting)' if not out_dir_overwrite else ''}",
            file=stderr,
        )

        self.create_out_dir(out_dir_overwrite)

        if args.debug:
            try:
                mkdir(f"{self.out_dir}/dbg")
            except OSError:
                pass  # exists

    def copy_file(self, name, to=None):
        """
        Copy the file `name` into `out_dir`. If `name` is not a relative path,
        it is looked for in `self.templates_path`.
        If `to` is given, the file is copied into `out_dir/to`.
        (All the directories subsumed by `to` must exist)
        ```
        in = name is relative ? templates_path/name : name
        out = to ? out_dir/to : out_dir
        cp in out
        ```
        """
        print(name, to)
        path = name if name[0] == "/" else pathjoin(self.templates_path, name)
        if to:
            shutilcopy(path, f"{self.out_dir}/{to}")
        else:
            shutilcopy(path, self.out_dir)


    def create_out_dir(self, overwrite_if_exists=False):
        try:
            mkdir(self.out_dir)
        except OSError:
            if overwrite_if_exists:
                print("The output dir exists, overwriting its contents", file=stderr)
                rmtree(self.out_dir)
                mkdir(self.out_dir)


    def copy_common_file(self, name):
        """
        Copy a template file that resides in vamos-common repo.
        """
        assert name[0] != "/", name
        path = pathjoin(dirname(__file__), "templates", name)
        shutilcopy(path, self.out_dir)

    def new_file(self, name):
        if name in self.args.overwrite_default:
            filename = "/dev/null"
        else:
            filename = pathjoin(self.out_dir, name)
            assert filename not in self._generated_files, (
                filename,
                self._generated_files,
            )
            self._generated_files.append(filename)
        return open(filename, "w")

    def get_path(self, name):
        return pathjoin(self.out_dir, name)

    def try_clang_format_file(self, name):
        from subprocess import run

        run(["clang-format", "-i", self.get_path(name)])

    def new_dbg_file(self, name):
        filename = pathjoin(self.out_dir, "dbg/", name)
        return open(filename, "w")

   #def gen_file(self, infile, outfile, values):
   #    """
   #    Generate file by replacing placeholders in the file of the form `@KEY@`
   #    with text generated by callback functions that write into a stream.
   #    The result is written into outfile.
   #    E.g.:
   #    ```
   #    def gen_sand(stream):
   #        stream.write('grains of sands'_

   #    gen_file('my_in.c.in', 'my.c', { '@SAND@' : gen_sand }
   #    ```

   #    If the callback is not a function but a string, the string is written into
   #    the stream instead.
   #    """
   #    if outfile in self.args.overwrite_default:
   #        return
   #    inpath = pathjoin(self.templates_path, infile)
   #    outpath = pathjoin(self.out_dir, outfile)
   #    with open(inpath, "r") as infl:
   #        with open(outpath, "w") as outfl:
   #            for line in infl:
   #                if "@" in line:
   #                    matches = self._key_re.split(line)
   #                    print(matches)
   #                    assert False
   #                    for v, s in values.items():
   #                        assert v.startswith("@"), v
   #                        assert v.endswith("@"), v
   #                        line = line.replace(v, s)
   #                outfl.write(line)


    def gen_config(self, infile, outfile, values):
        """
        (A simple version of `gen_file`, to be removed in the future.)

        Generate configuration file by replacing key-values pairs in the `infile`
        and writing the resulting file into `outfile`. Each key is of the form `@KEY@`
        and values is a dictionary mapping the keys into the values, e.g.:
        {"@A@": "value1", "@B" : "value2"}
        """
        if outfile in self.args.overwrite_default:
            return
        inpath = pathjoin(self.templates_path, infile)
        outpath = pathjoin(self.out_dir, outfile)
        with open(inpath, "r") as infl:
            with open(outpath, "w") as outfl:
                for line in infl:
                    if "@" in line:
                        for v, s in values.items():
                            assert v.startswith("@"), v
                            assert v.endswith("@"), v
                            line = line.replace(v, s)
                    outfl.write(line)

    def input_file(self, stream, name):
        """
        Write the contents of the file `name` into the stream `stream`.

        :param stream:  stream to write to
        :param name:  name of the file (residing in `self.templates_path`) to write into `stream`
        """
        inpath = pathjoin(self.templates_path, name)
        with open(inpath, "r") as infl:
            write = stream.write
            for line in infl:
                write(line)
